# Generated by Django 4.2.30 on 2026-08-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerprofile',
            options={'ordering': ['full_name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='approval_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
