# Generated by Django 4.2.30 on 2026-08-30 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_alter_partnerprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerUnavailableDate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=120)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_dates', to='partners.partnerprofile')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('partner', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PartnerDeviceToken',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255)),
                ('platform', models.CharField(default='android', max_length=20)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to='partners.partnerprofile')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('partner', 'token')},
            },
        ),
    ]
