# Generated by Django 4.2.30 on 2026-08-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerprofile',
            options={'ordering': ['full_name', 'created_at'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
