# Generated by Django 4.2.30 on 2026-10-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def copy_into_messages(apps, schema_editor):
    Ticket = apps.get_model('customers', 'SupportTicket')
    Message = apps.get_model('customers', 'SupportMessage')
    for ticket in Ticket.objects.all():
        first = Message.objects.create(ticket=ticket, sender='customer', author_id=ticket.user_id, body=ticket.message)
        Message.objects.filter(pk=first.pk).update(created_at=ticket.created_at)
        last_at = ticket.created_at
        if ticket.reply:
            reply = Message.objects.create(ticket=ticket, sender='support', body=ticket.reply)
            Message.objects.filter(pk=reply.pk).update(created_at=ticket.updated_at)
            last_at = ticket.updated_at
        Ticket.objects.filter(pk=ticket.pk).update(last_message_at=last_at, admin_read_at=last_at)


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0003_supportticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportticket',
            options={'ordering': ['-last_message_at', '-created_at'], 'verbose_name': 'Support chat', 'verbose_name_plural': 'Support chats'},
        ),
        migrations.AddField(
            model_name='supportticket',
            name='admin_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='customer_read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='last_message_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('customer', 'Customer'), ('support', 'Support')], max_length=20)),
                ('body', models.TextField(max_length=2000)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customers.supportticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(copy_into_messages, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='supportticket',
            name='message',
        ),
        migrations.RemoveField(
            model_name='supportticket',
            name='reply',
        ),
    ]
