# Generated by Django 4.2.30 on 2026-09-30 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_email_google'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='otprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'OTP request', 'verbose_name_plural': 'OTP requests'},
        ),
    ]
