# Generated by Django 4.2.30 on 2026-08-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_alter_address_options_alter_city_options'),
        ('bookings', '0003_alter_bookingassignment_options'),
        ('catalog', '0007_bathroom_detail_copy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Customers type this in the app. Saved in uppercase, e.g. WELCOME50.', max_length=40, unique=True)),
                ('title', models.CharField(help_text='Short label shown in admin and in the app after apply, e.g. Welcome offer.', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional internal notes. Not shown in the app.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed amount (₹)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='For percentage: 10 means 10% off. For fixed: 100 means ₹100 off.', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum package price (after catalog discount) required to use this coupon. 0 = no minimum.', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional cap for percentage coupons, e.g. 20% off up to ₹200. Leave blank for no cap.', max_digits=10, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total times this coupon can be used across all customers. Leave blank for unlimited.', null=True)),
                ('usage_limit_per_user', models.PositiveIntegerField(blank=True, default=1, help_text='How many times one customer can use this coupon. Leave blank for unlimited. Default is 1.', null=True)),
                ('valid_from', models.DateField(blank=True, help_text='Leave blank to start immediately.', null=True)),
                ('valid_until', models.DateField(blank=True, help_text='Leave blank for no expiry.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Turn off to hide this coupon from the app without deleting it.')),
                ('cities', models.ManyToManyField(blank=True, help_text='Leave empty to allow all cities.', related_name='coupons', to='locations.city')),
                ('packages', models.ManyToManyField(blank=True, help_text='Leave empty to allow all packages.', related_name='coupons', to='catalog.servicepackage')),
                ('services', models.ManyToManyField(blank=True, help_text='Leave empty to allow all services. Ignored if specific packages are selected.', related_name='coupons', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemption', to='bookings.booking')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='coupons.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['coupon', 'user'], name='coupons_cou_coupon__5ef611_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='couponredemption',
            constraint=models.UniqueConstraint(fields=('coupon', 'booking'), name='unique_coupon_booking_redemption'),
        ),
    ]
