# Generated by Django 4.2.30 on 2026-08-27 12:56

from django.db import migrations, models


def mark_selected_service_coupons(apps, schema_editor):
    Coupon = apps.get_model('coupons', 'Coupon')
    for coupon in Coupon.objects.all():
        if coupon.services.exists():
            coupon.apply_scope = 'selected_services'
            coupon.save(update_fields=['apply_scope'])


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='apply_scope',
            field=models.CharField(choices=[('all_services', 'All services'), ('selected_services', 'Selected services only')], default='all_services', help_text='All services = one code for every service. Selected services = this code only works on the services you pick below.', max_length=30),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Used only when “Selected services only” is chosen. Hold Ctrl/Cmd to pick more than one.', related_name='coupons', to='catalog.service'),
        ),
        migrations.RunPython(mark_selected_service_coupons, migrations.RunPython.noop),
    ]
