# Generated by Django 4.2.30 on 2026-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_compact_coupon_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(help_text='Customers type this in the app. Letters and numbers only, saved as WELCOME50.', max_length=40, unique=True),
        ),
    ]
