# Generated by Django 4.2.30 on 2026-08-20 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_method_payment_partner_share_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='partner_share_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='platform_commission_amount',
        ),
    ]
