# Generated by Django 4.2.30 on 2026-08-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-is_default', '-updated_at'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
    ]
