# Generated by Django 4.2.30 on 2026-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_city_service_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='coming_soon_message',
            field=models.CharField(blank=True, help_text='Optional copy when services are hidden on home. Leave blank for the default message.', max_length=220),
        ),
    ]
