# Generated by Django 4.2.30 on 2026-10-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app', models.CharField(choices=[('customer', 'Customer app'), ('partner', 'Partner app')], default='customer', max_length=20)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('latest_version', models.CharField(help_text='Newest version in the store. Older apps see an optional "Update" card. Like 1.4.0 — the version name from pubspec.yaml, without the +build number.', max_length=20)),
                ('min_supported_version', models.CharField(blank=True, help_text='Apps older than this are blocked until they update. Leave blank to never force. Like 1.4.0 — the version name from pubspec.yaml, without the +build number.', max_length=20)),
                ('store_url', models.URLField(help_text='Play Store / App Store page the Update button opens.')),
                ('message', models.CharField(blank=True, help_text='Optional text shown in the prompt, e.g. what is new.', max_length=220)),
            ],
            options={
                'verbose_name': 'App release',
                'ordering': ['app', 'platform'],
            },
        ),
        migrations.AddConstraint(
            model_name='apprelease',
            constraint=models.UniqueConstraint(fields=('app', 'platform'), name='unique_app_release_per_platform'),
        ),
    ]
