# Generated by Django 4.2.30 on 2026-10-06 00:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_package_inclusions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0005_patna_only'),
        ('common', '0001_app_release'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushCampaign',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short and clear, e.g. "20% off AC service this week".', max_length=65)),
                ('body', models.CharField(help_text='The message under the title.', max_length=240)),
                ('audience', models.CharField(choices=[('customers', 'Customers (customer app)'), ('partners', 'Professionals (partner app)')], default='customers', max_length=20)),
                ('target', models.CharField(choices=[('everyone', 'Everyone'), ('city', 'Everyone in one city'), ('person', 'One person')], default='everyone', max_length=20, verbose_name='send to')),
                ('recipient', models.CharField(blank=True, help_text='For "One person", e.g. 9876543210 or name@gmail.com.', max_length=120, verbose_name='phone or email')),
                ('screen', models.CharField(choices=[('home', 'Home'), ('service', 'A service'), ('package', 'A package'), ('refer', 'Refer & earn')], default='home', help_text='Professionals always land on their home screen.', max_length=20, verbose_name='opens on tap')),
                ('send_at', models.DateTimeField(blank=True, help_text='Leave blank to send right away.', null=True, verbose_name='schedule for')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', editable=False, max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('devices', models.PositiveIntegerField(default=0, editable=False, verbose_name='phones targeted')),
                ('delivered', models.PositiveIntegerField(default=0, editable=False)),
                ('failed', models.PositiveIntegerField(default=0, editable=False)),
                ('error', models.CharField(blank=True, editable=False, max_length=255)),
                ('city', models.ForeignKey(blank=True, help_text='For "Everyone in one city". Customers with an address or booking there; professionals who serve it.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='push_campaigns', to='locations.city')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to='catalog.servicepackage')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='push_campaigns', to='catalog.service')),
            ],
            options={
                'verbose_name': 'Push notification',
                'verbose_name_plural': 'Push notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='common_push_status_b16cff_idx')],
            },
        ),
    ]
