# Generated by Django 4.2.30 on 2026-10-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_push_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='app',
            field=models.CharField(choices=[('customer', 'Customer app'), ('partner', 'Bromet Legends (partner app)')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='audience',
            field=models.CharField(choices=[('customers', 'Customers (customer app)'), ('partners', 'Professionals (Bromet Legends app)')], default='customers', max_length=20),
        ),
    ]
