# Generated by Django 4.2.30 on 2026-10-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_partner_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apprelease',
            name='app',
            field=models.CharField(choices=[('customer', 'Customer app'), ('partner', 'Demess Legends (partner app)')], default='customer', max_length=20),
        ),
        migrations.AlterField(
            model_name='pushcampaign',
            name='audience',
            field=models.CharField(choices=[('customers', 'Customers (customer app)'), ('partners', 'Professionals (Demess Legends app)')], default='customers', max_length=20),
        ),
    ]
