# Generated by Django 4.2.30 on 2026-08-19 19:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assignment_status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='unassigned', max_length=30),
        ),
        migrations.CreateModel(
            name='BookingAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('reassigned', 'Reassigned')], default='pending', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='bookings.booking')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='partners.partnerprofile')),
            ],
            options={
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['partner', 'status'], name='bookings_bo_partner_e258c3_idx'), models.Index(fields=['booking', 'status'], name='bookings_bo_booking_8fd25c_idx')],
            },
        ),
    ]
