# Generated by Django 4.2.30 on 2026-08-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_assignment_status_bookingassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Partner job', 'verbose_name_plural': 'Partner jobs'},
        ),
    ]
