# Generated by Django 4.2.30 on 2026-08-30 19:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_coupon_booking_coupon_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stars', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_status',
            field=models.CharField(choices=[('none', 'Not started'), ('scheduled', 'Scheduled'), ('on_the_way', 'On the way'), ('arrived', 'Arrived'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='none', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_payment', 'Pending Payment'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['visit_status'], name='bookings_bo_visit_s_56e831_idx'),
        ),
        migrations.AddField(
            model_name='bookingrating',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='bookings.booking'),
        ),
    ]
