# Generated by Django 4.2.30 on 2026-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_visit_lifecycle_ratings_partner_ops'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completion_photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_photos/completed/'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_photo',
            field=models.ImageField(blank=True, null=True, upload_to='booking_photos/start/'),
        ),
    ]
