# Generated by Django 4.2.30 on 2026-10-04 08:32

import apps.bookings.models
import apps.bookings.models as apps_bookings_models
from django.db import migrations, models


def give_each_booking_its_own_code(apps, schema_editor):
    Booking = apps.get_model('bookings', 'Booking')
    for booking in Booking.objects.only('pk').iterator():
        Booking.objects.filter(pk=booking.pk).update(
            start_code=apps_bookings_models.generate_start_code()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_booking_completion_photo_booking_start_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='reschedule_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_code',
            field=models.CharField(default=apps.bookings.models.generate_start_code, help_text='Customer shares this code with the partner to start the service.', max_length=4),
        ),
        migrations.RunPython(give_each_booking_its_own_code, migrations.RunPython.noop),
    ]
