# Generated by Django 4.2.30 on 2026-08-23 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='headline',
            field=models.CharField(
                blank=True,
                help_text='Bold line on the service detail screen, above the description.',
                max_length=160,
            ),
        ),
        migrations.CreateModel(
            name='ServiceInclusion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('included', 'Includes'), ('excluded', 'Does not include')], max_length=16)),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='catalog.service')),
            ],
            options={
                'ordering': ['kind', 'sort_order', 'created_at'],
            },
        ),
    ]
