# Generated by Django 4.2.30 on 2026-08-24 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_service_headline_serviceinclusion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroSlide',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, help_text='Optional overlay on the customer home slider.', max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(blank=True, help_text='Upload the banner shown in the home slider.', upload_to='home_slides/')),
                ('image_url', models.CharField(blank=True, help_text='Or paste a https /media URL if you are not uploading a file.', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Home slider image',
                'verbose_name_plural': 'Home slider images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
