# Generated by Django 4.2.30 on 2026-08-24 11:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_homeheroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProcessStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, help_text="Optional square icon shown on How it's done.", upload_to='service_steps/')),
                ('image_url', models.CharField(blank=True, help_text='Or paste a https /media URL if you are not uploading a file.', max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='catalog.service')),
            ],
            options={
                'verbose_name': "How it's done step",
                'verbose_name_plural': "How it's done steps",
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AlterField(
            model_name='service',
            name='headline',
            field=models.CharField(
                blank=True,
                help_text='Large title on the service detail screen, e.g. “A Cleaner Bathroom, Every Day”.',
                max_length=160,
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(
                blank=True,
                help_text='Long paragraph under the headline on the service detail screen.',
            ),
        ),
    ]
