# Generated by Django 4.2.30 on 2026-08-24 11:55

from django.db import migrations


HEADLINE = 'A Cleaner Bathroom, Every Day'
DESCRIPTION = (
    'Keep your bathroom fresh, clean and guest-ready with regular bathroom cleaning. '
    'Our professionals clean key surfaces including the WC, washbasin, tiles and fittings, '
    'helping maintain cleanliness and everyday hygiene.'
)
INCLUDED = [
    'Cleaning of toilet bowl (inside and rim)',
    'Cleaning of washbasin and faucet',
    'Wiping of bathroom tiles and visible surfaces',
    'Cleaning of taps and fixtures',
    'Sweeping and mopping of bathroom floor',
    'Final wipe-down and deodorizing of the bathroom',
]
EXCLUDED = [
    'Deep cleaning such as tile grout scrubbing',
    'Removal of heavy mold or hard water stains',
    'Use of acid-based or strong descaling chemicals',
    'Cleaning of shower curtains or drains',
    'Shifting or relocating heavy items in bathroom',
]
STEPS = [
    ('Toilet cleaning', 'The toilet bowl is cleaned as the initial step of the process'),
    (
        'Surface cleaning',
        'All surfaces in the bathroom, such as the walls and tiles, are cleaned',
    ),
]


def forwards(apps, schema_editor):
    Service = apps.get_model('catalog', 'Service')
    ServiceInclusion = apps.get_model('catalog', 'ServiceInclusion')
    ServiceProcessStep = apps.get_model('catalog', 'ServiceProcessStep')
    service = Service.objects.filter(name='Bathroom Cleaning').first()
    if service is None:
        return

    service.headline = HEADLINE
    service.description = DESCRIPTION
    service.save(update_fields=['headline', 'description', 'updated_at'])

    service.inclusions.all().delete()
    for index, text in enumerate(INCLUDED):
        ServiceInclusion.objects.create(
            service=service,
            kind='included',
            text=text,
            sort_order=index,
        )
    for index, text in enumerate(EXCLUDED):
        ServiceInclusion.objects.create(
            service=service,
            kind='excluded',
            text=text,
            sort_order=index,
        )

    if not service.process_steps.exists():
        for index, (title, description) in enumerate(STEPS):
            ServiceProcessStep.objects.create(
                service=service,
                title=title,
                description=description,
                sort_order=index,
            )


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_serviceprocessstep'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
