# Generated by Django 4.2.30 on 2026-08-25 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_bathroom_detail_copy'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Upload the photo shown on home and service detail.',
                upload_to='catalog/services/',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.CharField(
                blank=True,
                help_text='Or paste a https /media URL if you are not uploading a file.',
                max_length=500,
            ),
        ),
    ]
